#!/bin/bash

# For the moment, this is a separate make script that call the make for our application and then
# links with the openACN stuff. We should be able to add this to the standard make file...


# Copyright (c) 2008, Electronic Theatre Controls, Inc.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of Electronic Theatre Controls, Inc. nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
#   $Id: mktest $
#
 
cc -O2 -std=c99 -pedantic -Wall -Wextra -Wno-uninitialized -D_XOPEN_SOURCE=600 -D_BSD_SOURCE=1  -Iinclude -I../acnsrc/include/arch-1 -I../acnsrc/platform/linux -I../acnsrc/include  -c -oobj/acntest.o acntest.c
ar rcs lib/acntest.a obj/acntest.o obj/acn_port.o  obj/aton.o obj/cid.o obj/discover.o obj/dmp.o obj/dmpmem.o obj/marshal.o obj/mcast_util.o obj/netsock.o obj/netxface.o obj/ntoa.o obj/pack.o obj/rlp.o obj/rlpmem.o obj/sdt.o obj/sdtmem.o obj/slp.o
cc lib/acntest.a -lpthread -o acntest

if [ "$OS" = "linux" ]
then
sudo ./acntest
fi

if [ "$OS" = "Windows_NT" ]
then
./acntest.exe
fi

if [ "$OS" = "" ]
then
  echo "You need to specify the OS"
  echo "export OS=Windows_NT or export OS=linux"
fi

